<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Business.Core\Business.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NugetPackageRest" Version="2.3.0" />
  </ItemGroup>

</Project>