<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MediatR" Version="11.1.0" />
    <PackageReference Include="FluentValidation" Version="11.1.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.1.0" />
  </ItemGroup>

</Project>